package com.smh.fbconnect.utils

import android.content.Context
import com.smh.fbconnect.R
import javax.inject.Inject

class DataStorage @Inject constructor(private val context: Context) {

    fun generateOpenedGeosText(countriesList: ArrayList<String>): String {

        return if (countriesList.isNotEmpty()) {
            context.getString(
                R.string.opened_geos,
                countriesList.joinToString(separator = ", ")
            )
        } else context.getString(R.string.no_opened_geos)

    }

    val countryCodes: Array<String> get() = arrayOf(
        "AU", "AT", "AZ", "AX", "AL", "DZ", "AS", "AI", "AO", "AD", "AQ", "AG", "AR", "AM", "AW", "AF",
        "BS", "BD", "BB", "BH", "BY", "BZ", "BE", "BJ", "BM", "BG", "BO", "BQ", "BA", "BW", "BR",
        "IO", "BN", "BF", "BI", "BT", "VU", "VA", "GB", "HU", "VE", "VG", "VI", "UM", "TL", "VN",
        "GA", "HT", "GY", "GM", "GH", "GP", "GT", "GN", "GW", "DE", "GG", "GI", "HN", "HK", "GD",
        "GL", "GR", "GE", "GU",
        "DK",
        "JE",
        "DJ",
        "DM",
        "DO",
        "EG",
        "ZM",
        "EH",
        "ZW",
        "IL",
        "IN",
        "ID",
        "JO",
        "IQ",
        "IR",
        "IE",
        "IS",
        "ES",
        "IT",
        "YE",
        "CV",
        "KZ",
        "KH",
        "CM",
        "CA",
        "QA",
        "KE",
        "CY",
        "KG",
        "KI",
        "CN",
        "KP",
        "CC",
        "CO",
        "KM",
        "CG",
        "CD",
        "CR",
        "CI",
        "CU",
        "KW",
        "CW",
        "LA",
        "LV",
        "LS",
        "LR",
        "LB",
        "LY",
        "LT",
        "LI",
        "LU",
        "MU",
        "MR",
        "MG",
        "YT",
        "MO",
        "MW",
        "MY",
        "ML",
        "MV",
        "MT",
        "MA",
        "MQ",
        "MH",
        "MX",
        "MZ",
        "MD",
        "MC",
        "MN",
        "MS",
        "MM",
        "NA",
        "NR",
        "NP",
        "NE",
        "NG",
        "NL",
        "NI",
        "NU",
        "NZ",
        "NC",
        "NO",
        "BV",
        "IM",
        "NF",
        "CX",
        "SH",
        "PN",
        "TC",
        "HM",
        "AE",
        "OM",
        "KY",
        "CK",
        "PK",
        "PW",
        "PS",
        "PA",
        "PG",
        "PY",
        "PE",
        "PL",
        "PT",
        "PR",
        "KR",
        "RE",
        "RU",
        "RW",
        "RO",
        "SV",
        "WS",
        "SM",
        "ST",
        "SA",
        "MK",
        "MP",
        "SC",
        "BL",
        "MF",
        "PM",
        "SN",
        "VC",
        "KN",
        "LC",
        "RS",
        "SG",
        "SX",
        "SY",
        "SK",
        "SI",
        "US",
        "SB",
        "SO",
        "SD",
        "SR",
        "SL",
        "TJ",
        "TH",
        "TW",
        "TZ",
        "TG",
        "TK",
        "TO",
        "TT",
        "TV",
        "TN",
        "TM",
        "TR",
        "UG",
        "UZ",
        "UA",
        "WF",
        "UY",
        "FO",
        "FM",
        "FJ",
        "PH",
        "FI",
        "FK",
        "FR",
        "GF",
        "PF",
        "TF",
        "HR",
        "CF",
        "TD",
        "ME",
        "CZ",
        "CL",
        "CH",
        "SE",
        "SJ",
        "LK",
        "EC",
        "GQ",
        "ER",
        "SZ",
        "EE",
        "ET",
        "GS",
        "ZA",
        "SS",
        "JM",
        "JP"
    )
}